### Obter todas as fontes com paginação e ordenação
GET http://localhost:8080/sources
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcyOTk5ODB9.LrL7d5iyG5fU60_2P7-GPVvIO1Ep9ea52uGkSG3Ln3U


###

### Obter uma fonte específica por ID
GET http://localhost:8080/sources/1
Content-Type: application/json

###

### Criar uma nova fonte
POST http://localhost:8080/sources
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcyOTk5ODB9.LrL7d5iyG5fU60_2P7-GPVvIO1Ep9ea52uGkSG3Ln3U

{
  "name": "Folha de São Paulo Comida",
  "url": "https://feeds.folha.uol.com.br/comida/rss091.xml",
  "user_id": 1
}

###

### Atualizar uma fonte existente
PUT http://localhost:8080/sources/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcyOTk5ODB9.LrL7d5iyG5fU60_2P7-GPVvIO1Ep9ea52uGkSG3Ln3U

{
  "name": "Minha Fonte Atualizada",
  "url": "https://minhafonteatualizada.com"
}

###

### Deletar uma fonte
DELETE http://localhost:8080/sources/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcyOTk5ODB9.LrL7d5iyG5fU60_2P7-GPVvIO1Ep9ea52uGkSG3Ln3U

###

### Carregar feed de uma fonte
GET http://localhost:8080/sources/load_feed/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTcyOTk5ODB9.LrL7d5iyG5fU60_2P7-GPVvIO1Ep9ea52uGkSG3Ln3U
