### Obter usuário específico por email
GET http://localhost:8080/users/test@example.com
Content-Type: application/json

###

### Criar um novo usuário
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "Isabela Mendes",
  "email": "gomesisabesla13@gmail.com",
  "password": "password"
}

###

### Deletar um usuário
DELETE http://localhost:8080/users/find_by_email/test@example.com
Content-Type: application/json

###

### Login de usuário
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "gomesisabesla13@gmail.com",
  "password": "password"
}

###

### Atualizar senha
POST http://localhost:8080/users/update_password
Content-Type: application/json

{
  "email": "test@example.com",
  "old_password": "password",
  "new_password": ""
}

###

### Encontrar usuário por id
GET http://localhost:8080/users/1
Content-Type: application/json
