version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_aggregator
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: smart-news-fetcher
    environment:
      - DB_DRIVER=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_SOURCE=root:root@tcp(db:3306)/news_aggregator
      - DB_NAME=news_aggregator
      - WEB_SERVER_PORT=:8080
      - JWT_SECRET_KEY=your_secret_key
      - JWT_EXPIRATION_MINUTES=60
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=matheusvidal140@gmail.com
      - SMTP_PASSWORD=uomq jtha ngvo achh
      - SMTP_FROM_EMAIL=matheusvidal140@gmail.com
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
